version: '3'

services:

  express:
    build:
      context: ../api
      dockerfile: ../docker/express/Dockerfile
    volumes:
      - ../api:/api
    ports:
      - "3000:3000"

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "27017:27017"

#  mongo-express:
#    image: mongo-express:latest
#    restart: unless-stopped
#    ports:
#      - "8082:8082"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
#      ME_CONFIG_MONGODB_SERVER: mongodb

  vue:
    build:
      context: ../app
      dockerfile: ../docker/vue/Dockerfile
    volumes:
      - ../app:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - CHOKIDAR_USEPOLLING=true