version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ../api:/var/www/html
      - ./laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: ecom
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TAGS: dev
      MYSQL_SERVICE: mysql
    networks:
      - laravel

  php:
    build:
      context: ../api
      dockerfile: ../docker/laravel/Dockerfile
    volumes:
      - ../api:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel


#  db:
#    image: mariadb:10.2
#    environment:
#      MYSQL_DATABASE: ${DATABASE_NAME}
#      MYSQL_USER: ${DATABASE_USER}
#      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#    ports:
#      - 3306:3306
#    volumes:
#      - db:/var/lib/mysql
#
#  vue:
#    build:
#      context: ../app
#      dockerfile: ../docker/vue/Dockerfile
#    volumes:
#      - ../app:/app
#    ports:
#      - "8081:8081"
