version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ../api:/var/www/html
      - ./laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: ecom
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_TAGS: dev
      MYSQL_SERVICE: mysql
    networks:
      - laravel

  php:
    build:
      context: ../api
      dockerfile: ../docker/laravel/Dockerfile
    volumes:
      - ../api:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  vue:
    build:
      context: ../app
      dockerfile: ../docker/vue/Dockerfile
    volumes:
      - ../app:/app
      - /app/node_modules
    ports:
      - "8081:8081"
    environment:
      - CHOKIDAR_USEPOLLING=true
